# -*- coding: utf-8 -*-
{
    'name': "Sale Costing",
    'summary': """This module helps to calculate sale price from the purchase agreement.""",
    'author': "Futurenet Technologies/Prabakaran-R",
    'website': "http://www.futurenet.in",
    'category': 'Sales',
    'version': '13.0.1',
    'depends': ['product', 'purchase_stock', 'sale_purchase', 'rims_dashboard', 'subscription_extended',  'sale_subscription',
                'base', 'crm', 'mm_crm', 'mail', 'mm_master', 'project_extended', 'crm_iap_enrich'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/datas.xml',
        'data/standard_paperformat.xml',
        'reports/contract_report.xml',
        'reports/standard_report.xml',
        'wizards/bid_received_warning_views.xml',
        'wizards/epo_upload_wd.xml',
        'views/configuration_views.xml',
        'views/sale_costing_views.xml',
        'views/crm_view.xml',
        'views/service_type.xml',
        'views/sale_views.xml',
        'views/product.xml',
        'views/epo_type_view.xml',
        'views/sale_costing_temp.xml',
        'data/email_template.xml',
        'views/contract.xml',
    ],
}
