from . import shipment_mode
from . import res_partner
from . import oppor_orderline
from . import purchase_requisition
from . import approval_config
from . import purchase
from . import purchase_approval_history
from . import purchase_config
from . import account_move
from . import res_company
from . import stock_picking
from . import sale
from . import product
from . import dsr